/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminStdView.java
 *
 * Created on Jan 17, 2011, 9:35:21 PM
 */

package UI.Panels;

import ProcessEngine.ProcessEngineMain;

/**
 *
 * @author Administrator
 */
public class EvaluateDataView extends javax.swing.JPanel {

    ProcessEngineMain processEngine;
    javax.swing.JComboBox jComboBoxDate;
    javax.swing.JComboBox jComboBoxPredictionModel;
    javax.swing.JComboBox jComboBoxPredictionHorizon;
    
    /** Creates new form AdminStdView */
    public EvaluateDataView(ProcessEngineMain processEngine, javax.swing.JComboBox jComboBoxDate, 
            javax.swing.JComboBox jComboBoxPredictionModel, javax.swing.JComboBox jComboBoxPredictionHorizon) {
        initComponents();
        processEngine = new ProcessEngineMain();
        this.processEngine = processEngine;
        this.jComboBoxDate = jComboBoxDate;
        this.jComboBoxPredictionModel = jComboBoxPredictionModel;
        this.jComboBoxPredictionHorizon = jComboBoxPredictionHorizon;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanelcomposemail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jButtontextareaClear = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jLabelnotification = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Evaluation View"));

        jLabel10.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel10.setText("Evaluate");

        jTextAreaOutput.setEditable(false);
        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOutput);

        javax.swing.GroupLayout jPanelcomposemailLayout = new javax.swing.GroupLayout(jPanelcomposemail);
        jPanelcomposemail.setLayout(jPanelcomposemailLayout);
        jPanelcomposemailLayout.setHorizontalGroup(
            jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelcomposemailLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanelcomposemailLayout.setVerticalGroup(
            jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtontextareaClear.setText("Clear");
        jButtontextareaClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtontextareaClear.setFocusable(false);
        jButtontextareaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontextareaClearActionPerformed(evt);
            }
        });

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jLabelnotification.setText("Select Model Paramenters and click Start to Evaluate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelcomposemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtontextareaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelcomposemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtontextareaClear)
                    .addComponent(jButtonStart)
                    .addComponent(jLabelnotification))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontextareaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontextareaClearActionPerformed
        this.jTextAreaOutput.setText("");
        this.jLabelnotification.setText("Select Model Paramenters and click Start to evaluate");
    }//GEN-LAST:event_jButtontextareaClearActionPerformed
    
    public void setTextArea(String text){
        this.jTextAreaOutput.setText(text);
    }
    
    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        this.jLabelnotification.setText("");
        this.jTextAreaOutput.setText("Evaluating...");
        String result = this.processEngine.evaluate(this.jComboBoxDate.getSelectedItem().toString(), 
                (this.jComboBoxPredictionModel.getSelectedItem().toString() + " " +
                this.jComboBoxPredictionHorizon.getSelectedItem().toString() ));
        this.jTextAreaOutput.setText(result);
    }//GEN-LAST:event_jButtonStartActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtontextareaClear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabelnotification;
    private javax.swing.JPanel jPanelcomposemail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOutput;
    // End of variables declaration//GEN-END:variables

}
