/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminStdView.java
 *
 * Created on Jan 17, 2011, 9:35:21 PM
 */

package UI.Panels;

import ProcessEngine.ProcessEngineMain;

/**
 *
 * @author Administrator
 */
public class PredictDataView extends javax.swing.JPanel {

    ProcessEngineMain processEngine;
    javax.swing.JComboBox jComboBoxDate;
    javax.swing.JComboBox jComboBoxPredictionModel;
    javax.swing.JComboBox jComboBoxPredictionHorizon;
    
    /** Creates new form AdminStdView */
    public PredictDataView(ProcessEngineMain processEngine, javax.swing.JComboBox jComboBoxDate, 
            javax.swing.JComboBox jComboBoxPredictionModel, javax.swing.JComboBox jComboBoxPredictionHorizon) {
        initComponents();
        processEngine = new ProcessEngineMain();
        this.processEngine = processEngine;
        this.jComboBoxDate = jComboBoxDate;
        this.jComboBoxPredictionModel = jComboBoxPredictionModel;
        this.jComboBoxPredictionHorizon = jComboBoxPredictionHorizon;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanelcomposemail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtontextAreaClear = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jLabelnotification = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Prediction View"));

        jLabel10.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel10.setText("Predict");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelcomposemailLayout = new javax.swing.GroupLayout(jPanelcomposemail);
        jPanelcomposemail.setLayout(jPanelcomposemailLayout);
        jPanelcomposemailLayout.setHorizontalGroup(
            jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanelcomposemailLayout.setVerticalGroup(
            jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jButtontextAreaClear.setText("Clear");
        jButtontextAreaClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtontextAreaClear.setFocusable(false);
        jButtontextAreaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontextAreaClearActionPerformed(evt);
            }
        });

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jLabelnotification.setText("Select Model Paramenters and click Start to process");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelcomposemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtontextAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelcomposemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtontextAreaClear)
                    .addComponent(jButtonStart)
                    .addComponent(jLabelnotification))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontextAreaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontextAreaClearActionPerformed
        this.jTextArea1.setText("");
        this.jLabelnotification.setText("Select Model Paramenters and click Start to process");
    }//GEN-LAST:event_jButtontextAreaClearActionPerformed
    
    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        this.jLabelnotification.setText("");
        this.jTextArea1.setText("Processing...");
        String result = this.processEngine.predict(this.jComboBoxDate.getSelectedItem().toString(), 
                (this.jComboBoxPredictionModel.getSelectedItem().toString() + " " +
                this.jComboBoxPredictionHorizon.getSelectedItem().toString() ));
        this.jTextArea1.setText(result);
    }//GEN-LAST:event_jButtonStartActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtontextAreaClear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabelnotification;
    private javax.swing.JPanel jPanelcomposemail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
